name: C/C++ CI

on:
  push:
    branches: [ main, automerge ]
  pull_request:
    branches: [ main, automerge ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install libevent-dev
    - run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
